AWSTemplateFormatVersion: 2010-09-09
Description: ---
Parameters: 
  DeliveryStreamARN:
    Type: String
    Description: Enter the ARN of the kinesis firehose delivery stream.

Resources:
  CWLtoKinesisRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ""
            Effect: Allow
            Principal:
              Service:
                - logs.ap-east-1.amazonaws.com
                - logs.ap-south-2.amazonaws.com
                - logs.ap-southeast-3.amazonaws.com
                - logs.ap-southeast-4.amazonaws.com
                - logs.ap-south-1.amazonaws.com
                - logs.ap-northeast-3.amazonaws.com
                - logs.ap-northeast-2.amazonaws.com
                - logs.ap-southeast-1.amazonaws.com
                - logs.ap-southeast-2.amazonaws.com
                - logs.ap-northeast-1.amazonaws.com
                - logs.ca-central-1.amazonaws.com
                - logs.eu-central-1.amazonaws.com
                - logs.eu-west-1.amazonaws.com
                - logs.eu-west-2.amazonaws.com
                - logs.eu-south-1.amazonaws.com
                - logs.eu-west-3.amazonaws.com
                - logs.eu-south-2.amazonaws.com
                - logs.eu-north-1.amazonaws.com
                - logs.eu-central-2.amazonaws.com
                - logs.me-south-1.amazonaws.com
                - logs.me-central-1.amazonaws.com
                - logs.sa-east-1.amazonaws.com
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "aws:SourceArn": !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*" #Add source and reec
      Path: "/"
      Policies:
        - PolicyName: Permissions-Policy-For-CWL
          PolicyDocument:
            - Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                  - "firehose:PutRecord"
                  Resource:
                  - !Ref DeliveryStreamARN

